export const stateCodes = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']

export const statesData = {
	'Alabama': { code: 'AL' },
	'Alaska': { code: 'AK' },
	'Arizona': { code: 'AZ' },
	'Arkansas': { code: 'AR' },
	'California': { code: 'CA' },
	'Colorado': { code: 'CO' },
	'Connecticut': { code: 'CT' },
	'Delaware': { code: 'DE' },
	'District of Columbia': { code: 'DC' },
	'Florida': { code: 'FL' },
	'Georgia': { code: 'GA' },
	'Hawaii': { code: 'HI' },
	'Idaho': { code: 'ID' },
	'Illinois': { code: 'IL' },
	'Indiana': { code: 'IN' },
	'Iowa': { code: 'IA' },
	'Kansas': { code: 'KS' },
	'Kentucky': { code: 'KY' },
	'Louisiana': { code: 'LA' },
	'Maine': { code: 'ME' },
	'Maryland': { code: 'MD' },
	'Massachusetts': { code: 'MA' },
	'Michigan': { code: 'MI' },
	'Minnesota': { code: 'MN' },
	'Mississippi': { code: 'MS' },
	'Missouri': { code: 'MO' },
	'Montana': { code: 'MT' },
	'Nebraska': { code: 'NE' },
	'Nevada': { code: 'NV' },
	'New Hampshire': { code: 'NH' },
	'New Jersey': { code: 'NJ' },
	'New Mexico': { code: 'NM' },
	'New York': { code: 'NY' },
	'North Carolina': { code: 'NC' },
	'North Dakota': { code: 'ND' },
	'Ohio': { code: 'OH' },
	'Oklahoma': { code: 'OK' },
	'Oregon': { code: 'OR' },
	'Pennsylvania': { code: 'PA' },
	'Rhode Island': { code: 'RI' },
	'South Carolina': { code: 'SC' },
	'South Dakota': { code: 'SD' },
	'Tennessee': { code: 'TN' },
	'Texas': { code: 'TX' },
	'Utah': { code: 'UT' },
	'Vermont': { code: 'VT' },
	'Virginia': { code: 'VA' },
	'Washington': { code: 'WA' },
	'West Virginia': { code: 'WV' },
	'Wisconsin': { code: 'WI' },
	'Wyoming': { code: 'WY' }
}